---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: style-book-front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: style-book-front
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
